### PR TITLE
Add help_for method

### PR DESCRIPTION
**Pull request by zorkian**
This adds the ability to insert in-page help. I've started by adding it
for the Role tag, and audited groups. We can expand this to add more
help for people as questions come up and whenever we think we might need
it.

### CODE REVIEW

**Comment by zorkian** [comment]
@tmildorf (do you get emails when I open PRs? or should I continue to ping you)

**Comment by tmildorf** [comment]
Yes, I do get the emails.

Sorry for delay.  Multitasking for the loss.

**Comment by tmildorf** [comment]
LGTM!  Would we prefer clicking the help on/off or displaying help on hover?

**Comment by zorkian** [comment]
I am not sure. I went with this, because I dislike hovering (often gets in the way/is surprising) but I'm flexible.

**Comment by tmildorf** [comment]
I'm mostly worried about discoverability here.  I went looking in exactly the right place because I saw your comment about where you added help stuff.  Maybe add a question mark icon to get user attention?

**Comment by zorkian** [comment]
It's got a dotted underline like is standard for these things? Isn't
that enough?

--
Mark Smith mark@qq.is


On Tue, Apr 14, 2015, at 12:40 PM, tmildorf wrote:
> I'm mostly worried about discoverability here. I went looking in
> exactly the right place because I saw your comment about where you
> added help stuff. Maybe add a question mark icon to get user
> attention?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dropbox/grouper/pull/18#issuecomment-93034974

**Comment by tmildorf** [comment]
I suppose.

**Pull request merged**
