### PR TITLE
Send email when group join requests are processed

### PR DESCRIPTION
**Pull request by rra**
When a group join request has been either actioned or cancelled,
send email to the affected person letting them know and including
the reason field.  Assumes that the user name is an email address,
but that appears to be a common assumption in Grouper already.

### CODE REVIEW

**Comment by rra** [comment]
I'm not at all sure how to test this effectively.  Is there a simple way to stand up a local instance of Grouper?

**Comment by herb** [comment]
Yes, a local instance is possible. If you follow the instructions in README and use virtualenv to pull down the dependencies it should Just Work(tm).

**Comment by rra** [comment]
Oh, doh, there are instructions right there.  Thanks!

**Comment by rra** [comment]
I've now tested this via a local instance with a modified dev configuration to enable sending email notifications.  Tested both the actioned and canceled states, with and without an expiration set, and the email looked good in all cases.

**Pull request merged**
